### ISSUE TITLE
1.12

### ISSUE THREAD

**Issue by LennyPenny** [MichaelHillcox/XRay-Mod#10]
Any plans of for update?

**Comment by MichaelHillcox** [comment]
Sure, I'll have to set up a new dev environment. I'll have a look :)

**Comment by MichaelHillcox** [comment]
Just noticed that forge doesn't currently have a stable build but I will work on a release the moment they've gotten a stable build.

**Comment by LennyPenny** [comment]
They got a pre release build that's really stable (used it for a week without a single problem)
Also they don't do breaking api changes from unstable to stable (that's why lots of mods are already updated), so it really doesn't matter when you do it :D
Your call tho

On Sun, Jun 18, 2017 at 11:06 AM, Michael Hillcox <notifications@github.com<mailto:notifications@github.com>> wrote:

Just noticed that forge doesn't currently have a stable build but I will work on a release the moment they've gotten a stable build.

**Comment by MichaelHillcox** [comment]
@LennyPenny https://mods.curse.com/mc-mods/minecraft/256256-advanced-xray#t1:other-downloads

All updated with a few fixed thrown in for free

**Comment by LennyPenny** [comment]
wuhuu thanks
