### ISSUE TITLE
The Rgb isnt working and wont work

### ISSUE THREAD

**Issue by Towhead1212** [MichaelHillcox/XRay-Mod#101]
**Describe the bug**

none of the rgb is working

**To Reproduce**
1. open the xray selection gui
2. turn on any ore
3. back out of the menu and turn it on1

**Expected behavior**
to see white outlines of diamond ore but all that i see is a dark shade of gray

**Screenshots**
If applicable (delete if not), add screenshots to help explain your problem.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2] 1.12.2
 - XRay Mod Version: [eg: 1.5.0] 1.6
 - Mod Pack & Version if applicable its a custom modpack so here's the list: 
![Screenshot (5)](https://user-images.githubusercontent.com/52182025/64902463-15617a80-d66d-11e9-9e77-1ae68863a3de.png)
![Screenshot (1)](https://user-images.githubusercontent.com/52182025/64902464-15617a80-d66d-11e9-8759-a14819c8be5d.png)
![Screenshot (2)](https://user-images.githubusercontent.com/52182025/64902465-15617a80-d66d-11e9-951e-cd8007bfb0c6.png)
![Screenshot (3)](https://user-images.githubusercontent.com/52182025/64902466-15617a80-d66d-11e9-9c9c-9ee2b8f975a9.png)
![Screenshot (4)](https://user-images.githubusercontent.com/52182025/64902467-15fa1100-d66d-11e9-80e8-ae54feced4d9.png)

 - Forge Version if applicable

**Additional context**

**Comment by asawula** [comment]
Check your forge version, XRay 1.6.0 supports Forge 14.23.0.2768.

**Comment by Towhead1212** [comment]
I have the latest 1.12 version

**Comment by MichaelHillcox** [comment]
I'm not going to dig through the screenshots. My guess is that you have a mod that effects the render layer of my mod. This is a common issue I find with other mods in the same tick event as mine runs in. If you could put the list of files in an actual searchable list I'd be happy to tell you which one it is.

**Comment by Towhead1212** [comment]
Ok I'll have it for you later

**Comment by asawula** [comment]
I am having the same gray only outline issue. Here is my mod list: Thanks!

AdChimneys-1.12.2-3.5.5.0-build.0402.jar
adminshop-1.3.2.jar
AmbientSounds_v3.0.9_mc1.12.2.jar
antiqueatlas-1.12.2-4.5.1 (1).jar
Apotheosis-1.12.2-1.10.5.jar
AppleCore-mc1.12.2-3.2.0 (1).jar
AppleSkin-mc1.12-1.0.9.jar
Artifacts-1.12.2-1.1.0.jar
astikorcarts-1.12.2-0.1.2.7.jar
athenaeum-1.12.2-1.17.3.jar
AtlasExtras-1.12.2-1.7.jar
AutoRegLib-1.3-32 (1).jar
BackTools-1.12.2-7.0.1.jar
BaseMetals-1.12-2.5.0-rc2.332.jar.disabled
Baubles-1.12-1.5.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
betterportals-0.2.7.jar.disabled
BetterQuesting-3.5.300.jar
BetterThanMending-1.1.2 (1).jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
Bloodmoon-MC1.12.2-1.5.3.jar
BowInfinityFix-1.12.2-rv5.1.jar
branders-enhanced-mob-spawners.v1.4.1-1.12.2.jar
BringMeTheRings-0.4.jar
Bullseye-1.12.2-3.0.7.jar
campfire-1.12-v1.2 (2).jar
Capsule-1.12.2-3.2.102.jar
CarryOn+MC1.12.2+v1.12.1.jar
cc-tweaked-1.12.2-1.84.0.jar
Charm-1.12.2-1.3.2.jar
chickens-6.0.4.jar
Chunk+Pregenerator+V1.12-2.1.jar
CleanView-1.12.2-v1c.jar
Clumps-3.1.2.jar
CoFHCore-1.12.2-4.6.3.27-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
ConfigurableCane-1.0.jar
Controlled+Burn-1.12.2.017.jar
CookingForBlockheads_1.12.2-6.4.71.jar
coroutil-1.12.1-1.2.32.jar
CraftTweaker2-1.12-4.1.19.jar
CreativeCore_v1.9.62_mc1.12.2.jar
CTM-MC1.12.2-0.3.3.22.jar
cttinycoal-1.12.2-1.0.2.jar
culinaryconstruct-1.3.3.jar
CustomNPCs_1.12.2(30Jan19).jar
CustomStartingGear-1.12-1.2.0.9-universal.jar
customstuff4-1.12.2-0.5.3.jar
delivery-1.12.2-1.5.2.jar
diethopper-1.1.jar
dirt2path-1.8.0 (1).jar
dropt-1.12.2-1.15.1.jar
dwmh-1.12.2-3.1.0.jar
DynamicSurroundings-1.12.2-3.5.4.3.jar
DynamicTrees-1.12.2-0.9.5.jar
DynamicTreesBOP-1.12.2-1.4.1e.jar
DynamicTreesPHC-1.12.2-1.4.2.jar
ElectroblobsWizardry-4.2.3-MC1.12.2.jar
enchantingbottles-1.0.jar
EnchantingTable-1.12-1.1.3 (1).jar
EnchantmentDescriptions-1.12.2-1.1.13.jar
endercrop-1.12.2-1.6.0.jar
enderpay-1.12.2-1.0.1.0 (1).jar
extraalchemy-0.5.1.jar
ExtraSpells-1.12.2-1.1.1 (1).jar
fairylights-2.1.9-1.12.2.jar
FamiliarFauna-1.12.2-1.0.11.jar
Farseek-1.12-2.3.2.jar
fencejumper-1.12-1.0.5.jar
FenceOverhaul-1.3.4 (1).jar
findme-1.12.2-1.1.0-8.jar
FlameLib-1.12.2-0.0.7.jar
Flood-1.0.1.jar
foamflower-1.12.2-1.0.0.0-beta1.jar
ForgeEndertech-1.12.2-4.4.22.2-build.0405.jar
fossilsarcheology-8.0.2.jar
FTBLib-5.4.3.130.jar
FTBQuests-1.7.2.189.jar
FTBUtilities-5.4.0.100.jar
fxcontrol-1.12-0.1.14.jar
GarbageBins-1.1.1.jar
Geolosys-1.12.2-3.0.2b.jar
grapplemod-v11.1-1.12.2.jar
HardcoreDarkness-MC1.12.2-2.0.jar
hatstands-1.0.0-1.12.2.jar
HungerOverhaul-1.12.2-1.3.3.jenkins148 (1).jar
hunterillager-1.12.2-1.2.jar
iceandfire-1.8.1.jar
iChunUtil-1.12.2-7.2.1.jar
IllagersPlus-1.12.2-1.1.3.jar
ImmersiveEngineering-0.12-91.jar
immersivepetroleum-1.12.2-1.1.9.jar
ImmersivePosts-0.1.3.jar
immersivetech-1.12-1.3.10.jar
incontrol-1.12-3.9.16.jar
instantunify-1.12.2-1.1.2 (1).jar
inventorysorter-1.12.2-1.13.3+57.jar
ItemFilters-1.0.3.12.jar
ItemPhysic_Full_1.4.21_mc1.12.2.jar
IvToolkit-1.3.3-1.12 (1).jar
Jack-O'-Launcher-1.12.2-1.7.0.jar
jeiintegration_1.12.2-1.5.1.36.jar
jei_1.12.2-4.15.0.268.jar
JustAFewFish-1.7_for_1.12 (1).jar.disabled
JustEnoughPetroleum-0.1.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
LagGoggles-FAT-1.12.2-4.8.jar
Level+Up!+2-1.1.23-1.12.jar
LibraryEx-1.12.2-1.0.11.jar
llibrary-1.7.19-1.12.2 (1).jar
LoadingProfiler-MC1.12-1.3.jar
Mantle-1.12-1.3.3.55.jar
maxpotidext-0.0.2.1 (1).jar
mcjtylib-1.12-3.5.4.jar
meecreeps-1.12-1.3.1.jar
minerva-library-1.0.13.jar
MMDLib-1.12-1.0.0-rc2.36.jar
MobController-1.12.2-1.1.jar
MobGrindingUtils-0.3.13.jar
modlist.txt
modlist1.txt
modnametooltip_1.12.2-1.10.1.jar
MonsterSwarm-2.0.1 (1).jar.disabled
morechickens-1.12.2-3.1.0.jar
moreoverlays-1.15.1-mc1.12.2.jar
MouseTweaks-2.10-mc1.12.2.jar
MultiMine-1.12.2.jar
multimob-1.0.5.jar
netherchest-1.1.1.jar
NetherEx-1.12.2-2.0.12.jar
nomoreglowingpots-1.2.jar
NPCIntegration-3.4.32.jar
Nutrition-1.12.2-4.0.0.jar
omlib-1.12.2-3.1.3-246.jar
oops-1.12-5.11.jar
openmodularturrets-1.12.2-3.1.3-355.jar
OptiFine_1.12.2_HD_U_E3.jar
OreLib-1.12.2-3.5.2.2.jar
outfox-0.1.4-mc1.12.2.jar
Pam's+HarvestCraft+1.12.2zf.jar
PassableLeaves-1.12.2-2.0.0.jar
PeacefulSurface-1.12.2-v1 (2).jar
pecunia-v1-3.jar
PetBat-1.12.2.jar
Placebo-1.12.2-1.6.0.jar
PotionCore-1.8_for_1.12.2.jar
primitivemobs-1.2.3a (1).jar
ProgressiveDifficulty-1.12_3.1.jar
QualityTools-1.0.6_for_1.12.2.jar
Quark-r1.6-177.jar
questbook-3.1.1-1.12.jar
RainingCatsAndDogs-1.12.2-1.0.0.jar
rats-2.0.0.jar
RealBench-1.12.2-1.3.3 (1).jar
realistic-cobwebs-1.12.2-1.0.4.jar
RealisticTorches-1.12.2-2.1.1 (1).jar
RecurrentComplex-1.4.8.2.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
Repose-1.12-1.6.4.jar
roadrunner-1.0.1 (1).jar
RoguelikeDungeons-1.12.2-1.8.0 (1).jar
roost-1.12-1.3.0.jar
rustic-1.1.1.jar
SaltyMod-1.12.2-1.12.6.0.jar
SeedsForWizardry+1.0+For+MC+Forge+1.12.2 (1).jar
SereneSeasons-1.12.2-1.2.16-universal.jar
signpost-1.12-1.06.1.jar
SimpleOreSamples-1.12-2.0 (1).jar
slideemall-1.0.jar
SnowAccumulation-1.12-1.0.0.jar
SnowRealMagic-0.3.2.jar
solcarrot-1.12.2-1.3.3 (1).jar
Sound-Physics-1.12.2.jar
SpartanShields-1.12.2-1.5.0.jar
SpartanWeaponry-1.12.2-beta-1.3.0.jar
SpiceOfLife-mc1.12-1.3.12.jar
stackable-1.12.2-1.3.3.jar
StandardExpansion-3.4.159.jar
stg-1.12.2-1.2.3 (2).jar
Streams-1.12-0.4.7.jar
sulfur-potassium-1.12-1.1.jar
Surge-1.12.2-2.0.77.jar
TConstruct-1.12.2-2.12.0.157.jar
theoneprobe-1.12-1.4.28.jar
Tips-1.12.2-1.0.7.jar
tnt_utilities-mc1.12-1.2.3.jar
tombstone-3.5.8-1.12.2.jar
ToolBelt-1.12.0-1.7.1.jar
topaddons-1.12.2-1.11.0.jar
vending-1.12.2-3.0.1.2.jar
VillageNames-1.12.2-3.2.1.jar
Waddles-1.12.2-0.6.0.jar
walljump-1.12.2-1.2.3.jar
wards-1.3.1.jar
Waystones_1.12.2-4.0.72.jar
WearableBackpacks-1.12.2-3.1.3.jar
weather2-1.12.1-2.6.12.jar
whopper-1.0.2.jar
WindowDressings_1.2.1.jar
WTS-1.1.0.jar
xpfromharvest-1.12.2-1.1.0.jar
xray-1.12.2-1.6.0.jar
[1.12.2]OrganicCreepers-1.2.5.jar

**Comment by MichaelHillcox** [comment]
Part of sorta. #102

**Comment by asawula** [comment]
Could you explain to me how this relates to #102 ? 
Neither disabling VBO rendering or removing optifine fix the problem for me.
If you could suggest which mods are likely culprits that would save me some time.
Thanks.

**Comment by MichaelHillcox** [comment]
moreoverlays-1.15.1-mc1.12.2.jar maybe or a maps mod?
