### ISSUE TITLE
Shader support

### ISSUE THREAD

**Issue by SoumyBhow** [MichaelHillcox/XRay-Mod#102]
I'm using Chocapic13 7.1.1 Toaster Edition Shaders but the x-ray doesn't highlight any of
my specified blocks.  It would be neat for the blocks to be outlined while using shaders at the same time so I don't have to keep turning off and on my shaders. 
I've attached a picture of the problem. The gold ores are supposed to have a yellow outline, but it doesn't show when shaders are on. I would greatly appreciate it if you are able to figure something out, but I understand if it's not possible.

![2019-09-23_21 00 17](https://user-images.githubusercontent.com/42043870/65473280-19e41b00-de45-11e9-8ec5-173a43a90a69.png)

**Comment by MichaelHillcox** [comment]
Can you confirm your version please.

**Comment by SoumyBhow** [comment]
Sure. Minecraft 1.14.4 (Forge 28.1.17), Chocapic13 7.1.1 Toaster Edition Shaders, Xray-1.14.4-2.0.0 mod.

**Comment by MichaelHillcox** [comment]
I'll see what I can figure out :D

**Comment by SoumyBhow** [comment]
Wait I think I found the problem. I had to disable VBO rendering in Optifine. It works now.

**Comment by MichaelHillcox** [comment]
Closed in preference of #140
