### ISSUE TITLE
Config isn't working

### ISSUE THREAD

**Issue by AriesStar1337** [MichaelHillcox/XRay-Mod#103]
Version 1.14.4-2.0.0
Config keep reset itself every time after enter world

+ Need a way to remove added block
Also need a way config added block (Since it can't be config or add the same block again)

**Comment by MichaelHillcox** [comment]
Damn, really? it should be doing that. You can also remove blocks, you just have to shift click on a block in the Gui and it'll open up an edit screen. On the right is a delete button. I'll check the config today :)

**Comment by MichaelHillcox** [comment]
This has been fixed :D
