### ISSUE TITLE
Can't add same block

### ISSUE THREAD

**Issue by AriesStar1337** [MichaelHillcox/XRay-Mod#104]
1.Add Block
2.Delete added block
3.Add Same Block
4.Nothing happen

Also block_store.json seem to reset every time. (Can't change / write)

**Comment by MichaelHillcox** [comment]
I'll take a look. Thanks for the report.

**Comment by MichaelHillcox** [comment]
A small note, the cache is generated every game load. You can just reload to fix this. I'll see whats wrong :P
