### ISSUE TITLE
Config file Resets

### ISSUE THREAD

**Issue by Cody799615** [MichaelHillcox/XRay-Mod#105]
The config file resets back to default every time you start Minecraft. It's very difficult to find ores with this fading effect on and I can't turn it off :(

**Comment by NoMaD76** [comment]
Hi Micheal, just wondering why this was closed? what is the solution please? As I been trying to figure out how to get past this problem, config reseting to default. the fade option I want to turn off and make the lines a bit thicker. so many other xray mods out there but this is the only one I found that is not intrusive to gameplay (not making every other block invisible etc) 
- great work btw!!! thank you :)
using forge 28.1.80 on 1.14.4 with optifine, not sure if that matters. I modded a bit on other games in the past but bit involved setting up it seems for minecraft jikes
Thanks mate
