### ISSUE TITLE
I need help i dont know how to update my forge version to 28.1.0 ·_·

### ISSUE THREAD

**Issue by PatotatoMan** [MichaelHillcox/XRay-Mod#106]
I just dont know i need help -_-

**Comment by PatotatoMan** [comment]
i just started playing minecraft yesterday so i dont know how to do it

**Comment by MichaelHillcox** [comment]
http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.14.4-28.1.0/forge-1.14.4-28.1.0-installer.jar 

Use this, the rest is done for you. Enjoy :D

**Comment by PatotatoMan** [comment]
Oh my word thanks a lot michael :D
