### ISSUE TITLE
Distance isn't right?

### ISSUE THREAD

**Issue by ElfKIngCyr** [MichaelHillcox/XRay-Mod#108]
**Describe the bug**
I've got it set to Distance-64, but after about 9 blocks I stop seeing the ore/block

**Expected behavior**
I thought that by setting the distance to 64, I would see all of those blocks within a radius of 64 block, is this wrong?

**Screenshots**
![Distance](https://user-images.githubusercontent.com/29515130/66351099-fb911b80-e92a-11e9-9eb6-d53144ba480c.png)
this screenshot shows when I stopped seeing the iron ore at the set distance

**Minecraft Environment**
 - Minecraft version 1.14.4
 - Advanced XRay // MC1.14.4-2.0.1
 - no other mods
 - Forge Version 1.14.4-forge-28.1.0

**Comment by ElfKIngCyr** [comment]
I had other mods on at the time of the screenshot, but I took them off and did the same tests, and got the same results.
I don't know if this is happening with other people or not.

**Comment by MichaelHillcox** [comment]
Turn off the fading effect but I'll sort out how aggressive the fading is. You can disable it in the config.

**Comment by pumbelixpl** [comment]
2.0.1 - Forge last version (.40)

![ies6ZMv](https://user-images.githubusercontent.com/56350534/66529292-33eb5200-eb03-11e9-96d5-770645d5c8b6.png)
![VnuOygE](https://user-images.githubusercontent.com/56350534/66529298-38176f80-eb03-11e9-9c29-c2461ad3fb11.png)

**Comment by keyascii** [comment]
> Turn off the fading effect but I'll sort out how aggressive the fading is. You can disable it in the config.

How do i change it in the config? i can't find it

**Comment by MichaelHillcox** [comment]
Its under shouldFade i think, it’ll be fixed soon.

**Comment by MichaelHillcox** [comment]
Fixed in next release :D
