### ISSUE TITLE
Ore dictionary support only half works.

### ISSUE THREAD

**Issue by Shalar** [MichaelHillcox/XRay-Mod#11]
I added this mod to my FTB Beyond, and it added copper ore but with it enabled and me standing right beside some, it shows nothing. Minecraft version is 1.10.2. I have checked the config and it seems OK. I even double checked to make sure that the ore is the same name. To be clear all vanilla ores work, but I have yet to get any modded ores to show. I even tried adding by ID:Meta, and all it did was freeze the ore selection for that to be on as in issue #3 because I added a duplicate ore.

**Comment by MichaelHillcox** [comment]
Which mod? You should be adding it by ID:META and not MODNAME:BLOCKNAME. I'm going to be back porting all the new changes in the latest 1.2.0 version of the mod soon. Although It's not on the top of my priority list. Make sure there isn't two blocks with the same ID:META in the config. If the ore is displayed as a ID:META and the meta is higher than 0 then just adding the ID will show all of the ores from that mod.

**Comment by Shalar** [comment]
The config file I used when making the screenshot below is here: [https://hastebin.com/adiwakasel.m]( https://hastebin.com/adiwakasel.m) As you can see I ignored ID:META in the oredict section and all vanilla blocks added this way are outlined, while every other block added does not work.
![2017-06-19_19 30 57](https://user-images.githubusercontent.com/1124482/27310189-909fed8c-5526-11e7-8028-0b3bbc6e88ee.png)

**Comment by MichaelHillcox** [comment]
Wow now. Thats a weird bug. I'll take a look at that one for you <3

**Comment by MichaelHillcox** [comment]
@Shalar What mod pack are you using?

**Comment by Shalar** [comment]
Feed the Beast BeyondOn Jun 20, 2017 10:08 AM, Michael Hillcox <notifications@github.com> wrote:@Shalar What mod pack are you using?

**Comment by Hexogenx** [comment]
Just to add in on this, cause I'm also playing on 1.10.2
I'm playing on Age of Engineering 1.01

Adding custom ores by ID:META does not work. Added a screenshot for Osmium Ore from Mekanism 7309:0 and Bauxite Ore from TechReborn 8403:4

![image](https://user-images.githubusercontent.com/16266686/27773703-f86a1420-5f7f-11e7-8ced-51261fde48e0.png)

Adding them manually to the cfg file using their oredict names does not work either. Added Osmium to the config with oreOsmium and Bauxite with oreAluminum and oreBauxite leaving ID and META set to 0 as the other items.

Things already in the cfg work, but added things don't

**Comment by MichaelHillcox** [comment]
I'll definitely be looking into why this is happening. My thinking is that I've fucked up the system that handles checking the oredic and then checking the config.

**Comment by MichaelHillcox** [comment]
I've found the issue and I'm working on a real fix now. Turns out Minecraft 1.10+ doesn't resolve the ID:META to the same form that the MODNAME:BLOCKNAME does so I'm updating it now :)

**Comment by MichaelHillcox** [comment]
@Shalar @Hexogenx Please see 
https://github.com/MichaelHillcox/XRay-Mod/releases/tag/1.10.2-v1.2.1 or https://minecraft.curseforge.com/projects/advanced-xray/files/2445838 for the updated version <3

**Comment by Shalar** [comment]
This issue still exists when using the oredict section. It however has been fixed when adding an ore to the customores.

**Comment by MichaelHillcox** [comment]
So oredict stuff is still having an issue. I think I'm gunna rewrite the whole adding system. At least adding custom ones is now fixed :) I'm gunna make a new issue
