### ISSUE TITLE
Metadata change

### ISSUE THREAD

**Issue by niklas2233** [MichaelHillcox/XRay-Mod#113]
Hey is there a way to make it so you can enable metadata specific blocks cause thermal foundation uses same id but different metadata for their ores and sometimes its really annoying when you just want a specific ore from that mod. if you make this change plz do it on the 1.12.2 version aswell since thats the version im playing on atm :)

would also be nice if you add so its possible to add oreDict tags as searchable blocks

**Comment by Dbboli01** [comment]
I relay hope the mod maker adds oreDict support and meta data support that whould be amazing

**Comment by Dbboli01** [comment]
Well so i just learned if you add thermal foundation ores by looking at the block and doing it that way it works and dose not show all thermal foundation ores

**Comment by MichaelHillcox** [comment]
^ the above comment is the solution to this for 1.12, in later versions of the mod this is not an issue as mods are not meant to add ore varients based on meta data. Use Looking At instead of the Gui based block list.
