### ISSUE TITLE
Rendering GUI Crash

### ISSUE THREAD

**Issue by WenXin20** [MichaelHillcox/XRay-Mod#115]
**Describe the bug**
As soon as I pressed `g`, my game froze and then crashed.

**To Reproduce**
1. Press `g` to open the x-ray menu
2. Crash

**Expected behavior**
It shouldn't crash.

**Minecraft Enviorment**
 - Minecraft Version: 1.14.4
 - XRay Mod Version: 2.0.2
 - Forge Version: 28.1.116

**Additional context**
[Crash Report](https://gist.github.com/WenXin20/8f7276cd47c3f534b45d5968fd3485f9)

**Comment by MichaelHillcox** [comment]
That crash makes no sense at all. Can you reproduce it?

**Comment by WenXin20** [comment]
I've had it happen before. Could a keybinding conflict cause it?

**Comment by MichaelHillcox** [comment]
Just for fun, can you try the latest release? 1.14.4-2.0.3 (Forge has been updated and so has some of the gui code)

**Comment by WenXin20** [comment]
Sure! I'll try it out later.

**Comment by MichaelHillcox** [comment]
Closed due to updated mod and lack of updates. Let me know if this is still an issue.
