### ISSUE TITLE
New blocks added do not show up in the list

### ISSUE THREAD

**Issue by Brinkwolf** [MichaelHillcox/XRay-Mod#119]
The blocks that are pre-added (ores like Diamond or Emerald) will work until you remove them from the list.
Trying to add blocks to the list does absolutely nothing.
Checked config, the blocks are set to "=true" but do not show up in the list in-game or get highlighted when xray is enabled.

I see that there are similar issues posted back in 2018 that seem to have been resolved, however my solution does not seem to be that easy.

**EDIT: Minecraft 1.12.2, probably should have mentioned that**

[GIF](https://gyazo.com/37256bad95e53353ac5bb31ca891d98a)

**Comment by MichaelHillcox** [comment]
This looks like a super old version. What version are you using?

**Comment by Brinkwolf** [comment]
OH, you replied while i was editing my original test lmao
Minecraft1.12.2, Xray version 1.4.1

**Comment by MichaelHillcox** [comment]
You're on an old version. For 1.12 we went up to 1.6.0 https://github.com/MichaelHillcox/XRay-Mod/releases/tag/1.12.2-v1.6.0

**Comment by Brinkwolf** [comment]
That makes sense. Whatever link i clicked took me straight to 1.4.1.
Thanks!
