### ISSUE TITLE
I am unable to remove a block from the block list.

### ISSUE THREAD

**Issue by Skies4ever** [MichaelHillcox/XRay-Mod#12]

**Comment by MichaelHillcox** [comment]
At the moment, until I rewrite how the UI functions. You'll have to remove it manually from the `customores` section in the `xray.cfg` or `fgtxray.cfg`

**Comment by MichaelHillcox** [comment]
This has now been added as of https://github.com/MichaelHillcox/XRay-Mod/tree/1.12-v1.3.0
