### ISSUE TITLE
accuracy issue

### ISSUE THREAD

**Issue by Hiold** [MichaelHillcox/XRay-Mod#120]
**Describe the bug**
many mods ore like Thermal Expansion,Immersive Engineering, the ore has same id. like TF.resource
when i add one kind of ore , this mod cant not mark them accuracy, its mark all the ore blocks

**To Reproduce**
1. Go to 'add block'
2. chose one kind of ore
3. Click add block

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.6.0
 - Forge Version:14.23.5.2847

**Comment by MichaelHillcox** [comment]
Use: Looking At instead of adding it via the Add Block. The Looking at uses the full block state and not just the default one.
