### ISSUE TITLE
nothing showing up

### ISSUE THREAD

**Issue by JORDZIE** [MichaelHillcox/XRay-Mod#122]
when i selct a bunch of ores and nothing shows up when i toggle on wherever i go

**Comment by MichaelHillcox** [comment]
Using shaders? got a version for me?

**Comment by JORDZIE** [comment]
1.15.2 on all the mods. Turned off shaders I had no problem with 1.12.2 with modpacks

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by MichaelHillcox** [comment]
Did it work once shaders were turned off?

**Comment by JORDZIE** [comment]
Not at all

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by JORDZIE** [comment]
I have optifine installed

Sent from Outlook Mobile<https://aka.ms/blhgte>
________________________________

**Comment by MichaelHillcox** [comment]
Hmm, maybe try without that, I need to update the rendering anyway but haven't been able to update it yet.

**Comment by JORDZIE** [comment]
ok will do when i get a chance.thanks

**Comment by robman33** [comment]
FYI, Had the same issue, removed optifine and it works again.

**Comment by MichaelHillcox** [comment]
Closed in preference of #140
