### ISSUE TITLE
Border collor issue

### ISSUE THREAD

**Issue by Vizis** [MichaelHillcox/XRay-Mod#124]
**Describe the bug**
Blocks border is allways gray no matter what color is set

**Minecraft Enviorment**
 - Minecraft Version:  1.12.2
 - XRay Mod Version:  1.6.0
 - forge-1.12.2-14.23.5.2847

**Comment by MichaelHillcox** [comment]
Are you using optfine?

**Comment by Vizis** [comment]
yes

**Comment by MichaelHillcox** [comment]
Closed in preference of #140 as well as #45 

You've likely got a mod that conflicts with my render. If you can figure out which mod it is, please let me know and I'll see if I can fix it.
