### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by bloodyearth** [MichaelHillcox/XRay-Mod#127]
**Describe the bug**
I just installed Forge and Advanced XRay, but the game crashes on load.

**To Reproduce**
1. Download and install Forge 14.23.5.2854.
2. Download and install Advanced XRay 1.6.0.
3. Launch the game.

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.6.0
 - Forge Version: 14.23.5.2854

**Additional context**
Crash-report: https://hastebin.com/fapelelaza.php

**Comment by MichaelHillcox** [comment]
Remove the xray/.json file in the config folder

**Comment by bloodyearth** [comment]
lol, thanks a lot, it works. : D
