### ISSUE TITLE
Xray not working with Optifine using shaders

### ISSUE THREAD

**Issue by soloHolo** [MichaelHillcox/XRay-Mod#128]
**Describe the bug**
Ores are not highlighted while using shaders running optifine version 1.15.2_HD_U_G1_pre17

**To Reproduce**
1. have shaders installed(currently using sildurs vibrant shader)
2. put a block in the list to be shown in xray mode
3. activate xray

**Expected behavior**
ore/blocks that are in the xray list isnt highlighted 

**Minecraft Enviorment**
 - Minecraft Version: [1.15.2]
 - XRay Mod Version: [2.2.0]
 - Forge Version: 31.1.77

**Comment by MichaelHillcox** [comment]
Could you try this version out for me and let me know if it fixes your issues https://s.mikey.pro/xray-1.15.2-2.2.1.jar it's got crap performance at the moment but It's an attempt to fix this issue.

**Comment by soloHolo** [comment]
Still doesnt display any block highlights. This might be an issue of the current optifine version.

**Comment by MichaelHillcox** [comment]
This was one of my best attempts to resolve rendering issues with optifine... Damn.

**Comment by pjtnt11** [comment]
I also am having issues where the highlights aren't showing, when I use OptiFine (1.15.2 HD U G1 pre17) and I'm not even using shaders. Works perfectly when OptiFine is completely disabled. I'm just speculating, but to me this sounds like an Optifine issue especially given that 1.15.2 only has preview versions out right now.

**Comment by soloHolo** [comment]
Optifine is quite a mess right now when using other mods...

**Comment by MichaelHillcox** [comment]
Optifine is closed source and has very little documentation. This issue has been present for years, since version 1 of this mod so I don't think it'll be solved any time soon. I've reached out to other modders but haven't been able to trackdown a cause unfortunatly.

**Comment by MichaelHillcox** [comment]
Closed in preference of #140
