### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Maxx9595** [MichaelHillcox/XRay-Mod#130]
I crash when I try to use the x-ray enable or the interface. I am using Forge 1.15 and X-ray 1.14, please help. Thanks!

[crash-2020-05-30_16.28.31-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/4706408/crash-2020-05-30_16.28.31-client.txt)

**Comment by MichaelHillcox** [comment]
You're using the wrong version of Forge or the wrong version of the mod. I have a 1.15 version of the mod.
