### ISSUE TITLE
Compatibility with Shaders and optifine 1.15.2

### ISSUE THREAD

**Issue by JaviDBG** [MichaelHillcox/XRay-Mod#131]
incompatible with OptiFine_1.15.2_HD_U_G1_pre19 you will not see the ore lines unless you disable the shaders.

It would be a great option that in the future the ore lines would be seen in any shader

**Comment by MichaelHillcox** [comment]
As OptinFine is still in pre-release and it is closed source, par from contacting the creator, I have no way to resolve this issue, sorry.

**Comment by MichaelHillcox** [comment]
Worth a chance try @sp614x do you know why my render code is not rendered when using optifine with shaders?  

My render code:
https://github.com/MichaelHillcox/XRay-Mod/blob/1.15.x/src/main/java/com/xray/xray/Render.java#L24-L87

**Comment by kpopstar1** [comment]
Hi, I just wanted to share a rare experience i had. I dl this mod and used it on my MC that was already running forge and optifine. The first time I ran MC, this mod actually worked fine with optifine(+shader). I loaded a world i was previously exploring and it worked well. After a while I closed the game and ran it again. I tried to use it on a new world but it doesnt work anymore. Just an fyi.

**Comment by MichaelHillcox** [comment]
Closed in preference of #140
