### ISSUE TITLE
incompatible with OptiFine

### ISSUE THREAD

**Issue by JaviDBG** [MichaelHillcox/XRay-Mod#132]
incompatible with OptiFine_1.15.2_HD_U_G1_pre19 you will not see the ore lines unless you disable the shaders (any shader).

**Minecraft Enviorment**
 - Minecraft Version: 1.15.2
 - XRay Mod Version: 1.15.2-2.2.0
 - Forge Version: 31.1.74

**Comment by MichaelHillcox** [comment]
Duplicate
