### ISSUE TITLE
liquid toggle

### ISSUE THREAD

**Issue by YokujinKaze** [MichaelHillcox/XRay-Mod#134]
would it be possible to add some toggle to hide/show lava and water blocks?

**Comment by MichaelHillcox** [comment]
This is already a thing for lava :D I plan in improving the support for this feature over time, any specific usecase you have for water?

**Comment by YokujinKaze** [comment]
no disabling the actual blocks not the wireframes

**Comment by MichaelHillcox** [comment]
Very unlikely to do this. I try to avoid any modifications that might interfere with other mods.
