### ISSUE TITLE
Fabric support?

### ISSUE THREAD

**Issue by YokujinKaze** [MichaelHillcox/XRay-Mod#139]
support for fabric loader?

**Comment by MichaelHillcox** [comment]
On it's way :D The repo is private atm but I will be releasing a Fabric version soon.

**Comment by YokujinKaze** [comment]
ah good and while on it a suggestion for both version:
let us choose/toggle between wireframe box or face highlight

**Comment by MichaelHillcox** [comment]
Face highlight? As in a full (filled in) cube render around the block?

**Comment by YokujinKaze** [comment]
yes with some transparency and color

**Comment by MichaelHillcox** [comment]
I can do that :D

**Comment by PixelTomato** [comment]
Any updates on Fabric support? I see that the last activity in this issue is from July and I'm just making sure that this is still being worked on. I'm creating a Fabric mod that requires block rendering to be disabled for certain blocks and I am very interested to see how you go about implementing it.

**Comment by randomairborne** [comment]
Will the 1.16.4 version support fabric?

**Comment by PixelTomato** [comment]
> Also, could you make the fabric repo public if not, so that we can update it?

I second that 😃 If you publish what you have so far, we can help take it the rest of the way.

**Comment by randomairborne** [comment]
or someone could fork the forge version, to make a fabric version

**Comment by MichaelHillcox** [comment]
For anyone interested in the progress https://github.com/MichaelHillcox/XRay-Fabric it’s just not super high on my work load

**Comment by randomairborne** [comment]
does it work at all, just inefficiently, or does it break? also thanks!

**Comment by MichaelHillcox** [comment]
Kinda, the scanning process has been roughed in and I've got the render running, It's mostly lacking the configurability and GUI of which I wanted to update and improve upon from what this mod currently has.

**Comment by randomairborne** [comment]
Looks like I've found a project worth helping with!  is there a discord that I could use for this mod, so as to not ask questions ETC on the GitHub?

**Comment by MichaelHillcox** [comment]
It's just me but you can add me on discord if you want :P MiKeY#3704

**Comment by randomairborne** [comment]
1. There is a discord now. [invite](https://discord.gg/2yDQgvGKzq)
2. Fabric edition now has a release: [CurseForge](https://www.curseforge.com/minecraft/mc-mods/advanced-xray-fabric-edition) [GitHub](https://github.com/MichaelHillcox/XRay-Fabric)
