### ISSUE TITLE
Add some config stuff

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/XRay-Mod#14]
- [ ] Outline thickness
- [ ] Outline Opacity
- [ ] Ability to enable a hex input 
- [ ] Ability to enable a rgb input 
- [ ] Options to balance 
Things like
  - [ ] Rapid hunger drain to prevent people from over using it
  - [ ] Radius affect instead of just 0 -> 999 range on the Y axis
  - [ ] Disable if you go into an MP server

**Comment by NatoBoram** [comment]
Add opacity to the lines

**Comment by MichaelHillcox** [comment]
Great idea :)

**Comment by MichaelHillcox** [comment]
I've added some of these and the rest shall be considered at a later date

**Comment by NatoBoram** [comment]
Can you edit the first message to check the checkboxes that are done?

**Comment by MichaelHillcox** [comment]
The first two have been changed because the prep is there but I need to find a good way of setting it all up.
