### ISSUE TITLE
Crashing on Opening GUI

### ISSUE THREAD

**Issue by NoohAlavi** [MichaelHillcox/XRay-Mod#143]
**Describe the bug**
When I open the GUI, sometimes my game just freezes up and crashes. However, sometimes it does work.

**To Reproduce**
1. Create new world or join existing world
2. Click on "G" or whatever keybind the GUI is attached to

**Expected behavior**
GUI to open without crashes

**Screenshots**
![image](https://user-images.githubusercontent.com/59208101/87841498-b44d9900-c873-11ea-9e2f-7e713b19f668.png)

**Minecraft Environment**
 - Minecraft Version: 1.16.1
 - XRay Mod Version: 2.3.1
 - Optifine + Forge 1.16.1
 - I also have the latest version of Java installed, updated today

**Additional context**
Usually, the game crashes if I reopen the GUI after closing it

**Comment by MichaelHillcox** [comment]
Can you submit a crashlog as well

**Comment by NoohAlavi** [comment]
@MichaelHillcox Didnt happen again yet, if it does, then I'll post an update here.

**Comment by MichaelHillcox** [comment]
Yeah, my recommendation is Update forge :+1: If you're still having issues, please reopen this issue
