### ISSUE TITLE
Advanced XRay (xray) has failed to load properly

### ISSUE THREAD

**Issue by ColinTheShark** [MichaelHillcox/XRay-Mod#144]
**Describe the bug**
When starting up Minecraft, Forge reports that XRay failed to load properly.
This happened with `OptiFine 1.16.1 HD U G2 pre10` and `Forge 1.16.1 - 32.0.93`.

**To Reproduce**
1. Launch Minecraft.

**Expected behavior**
I would have expected to land in the main menu of the game.

**Screenshots**
https://i.imgur.com/XDhMJtV.png

**Minecraft Enviorment**
 - Minecraft Version: `1.16.1`
 - XRay Mod Version: [`2.3.1`](https://github.com/MichaelHillcox/XRay-Mod/releases/tag/1.16.1-2.3.1)
 - Forge Version: `Forge 1.16.1 - 32.0.93`

**Additional context**
I have several other mods in my folder, such as Xaero's [Mini-](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) and [Worldmap](https://www.curseforge.com/minecraft/mc-mods/xaeros-world-map), [Giselbaer's Durabilityviewer](https://www.curseforge.com/minecraft/mc-mods/giselbaers-durability-viewer), [Shulker Tooptip](https://www.curseforge.com/minecraft/mc-mods/shulker-tooltip). Lastly there's also [AppleSkin](https://www.curseforge.com/minecraft/mc-mods/appleskin).

I have pasted my `latest.log` over on Pastebin: https://pastebin.com/raw/zAE90465

**Comment by MichaelHillcox** [comment]
Thanks for this, nice and quick fix. I'm releasing it now :D

**Comment by ColinTheShark** [comment]
Gotta love it, thanks :D

**Comment by MichaelHillcox** [comment]
Basically Forge updated their EventBus system to actually error check events configured to the wrong Event Bus. I wasn't the original implementor of the code that caused the crash so I never thought to make sure it was the right event... Now I've moved it onto the right event bus it's no longer causing the game to crash. The only way for me to have been able to tell would have been to investigate the issue but I never knew it was one until today 👍

**Comment by ColinTheShark** [comment]
Oh I see, I checked the commit earlier and there was some mentions of Event and some shuffling about haha

And you're welcome :D
