### ISSUE TITLE
Doesn't work as intended

### ISSUE THREAD

**Issue by walent021** [MichaelHillcox/XRay-Mod#145]
**Describe the bug**
The mod shows that there are the supposed blocks, but when getting near to the "blue outlines", it just disappears.

**To Reproduce**
Select a block to be shown in x-ray
Behavior only in multiplayer

**Expected behavior**
It should show where the particular block is located

**Minecraft Enviorment**
 - Minecraft Version: 1.16.1
 - XRay Mod Version: 2.3.2

**Comment by MichaelHillcox** [comment]
I do not support using thid mod in mutliplayer. It would appear to be an anti-xray feature from some servers plugins. Sorry about that.
