### ISSUE TITLE
How do i change keybinds for activating the xray?

### ISSUE THREAD

**Issue by thejekky** [MichaelHillcox/XRay-Mod#147]
Minecraft version 1.12.2
Xray version [1.5.0]
Forge version [14.23.5.2854]

So i just downloaded the mod and went to test it out so i pressed backslash to turn it on [with some ores activated] and nothing happened so then searched for a bit to figure out if i could change the keybind and i couldnt find anything. [sorry for my terrible grammar im brazilian] [also im not sure if youve added the change keybind feature yet or not]

**Comment by MichaelHillcox** [comment]
Controls in the main game settings :D
