### ISSUE TITLE
Mod wont work and crashes.

### ISSUE THREAD

**Issue by Robomnz** [MichaelHillcox/XRay-Mod#149]
**Describe the bug**
x ray mode doesnt go xray and highlight ores, also the menu crashes the game when trying to open it

**To Reproduce**
1. install the mod and launch minecraft
2. go into the game and activate xray mode and you will find it wont work
3. if you open the menu by hitting whatever hotkey you have set it to will crash the game

**Expected behavior**
to be able to see ores through stone blocks and be able to open the menu without a crash

**Screenshots**
![image](https://user-images.githubusercontent.com/34904608/90943955-4ac33a80-e470-11ea-9158-dcfbab39b90f.png)

**Minecraft Enviorment**
 - Minecraft Version: 1.16.2
 - XRay Mod Version: 1.16.2-2.4.0
 - Mod Pack & Version: none but currently using HWYLA, JEI and Xaeros minimap
 - Forge Version: 1.16.2-forge-33.0.5

**Additional context**
crash report when opening menu:
[crash-2020-08-22_11.54.04-client.txt](https://github.com/MichaelHillcox/XRay-Mod/files/5111705/crash-2020-08-22_11.54.04-client.txt)

**Comment by Grant-K** [comment]
> I'm going to go ahead and recommend updating Forge as this works fine for me

Im on the latest release of 1.16.2 forge still crashes

**Comment by Robomnz** [comment]
okie dokie will try that!
