### ISSUE TITLE
Minecraft crashes everytime with xray

### ISSUE THREAD

**Issue by ghostlypink** [MichaelHillcox/XRay-Mod#15]
hi here is my log.  I do have the latest Liteloader & Forge also latest Java. a mod I use for Liteloader is called mod_voxelMap_1.6.22_for_1.12.0.litemod. I've tried troubleshooting as far as removing files, and replaceing. It's sertainly the xray file. I also tried deleting, xray.cfg file. 

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from XRay (xray)

here's the pastebin embed link; <script src="https://pastebin.com/embed_js/MQyA1zfp"></script>

Please and thank you. 
signed Minecraft Enthusiast

**Comment by MichaelHillcox** [comment]
Hi, 
I've come accross this error before. From what I know it's an issue with an older version of forge for 1.12 can you try the latest release of forge and tell me if the issue persits.

**Comment by MichaelHillcox** [comment]
Gunna close this one. feel free to an a comment if this is still happening 👍

**Comment by vanishernl** [comment]
Hi, it is still happening, latest forge:
https://pastebin.com/V8gmzKSY

**Comment by MichaelHillcox** [comment]
Did you delete your config file? I forgot to put the note in the changelog

**Comment by vanishernl** [comment]
Which config file?

**Comment by MichaelHillcox** [comment]
xray.cfg

**Comment by vanishernl** [comment]
Great, working again!

**Comment by MichaelHillcox** [comment]
:)
