### ISSUE TITLE
this mode does not distinguish between the subnumbers of the block (eg wool #35/0, green wool #35/13).

### ISSUE THREAD

**Issue by minejango2** [MichaelHillcox/XRay-Mod#151]
**Describe the bug**
This mode has an error that does not distinguish between the subnumbers of the block (eg wool #35/0, green wool #35/13).

**Expected behavior**
when I want to find a white wool, it displays all colors of wools.

**Minecraft Enviorment**
 - Minecraft Version: [1.12.2]
 - XRay Mod Version: [1.6.0]

**Comment by MichaelHillcox** [comment]
Use looking at :)

**Comment by minejango2** [comment]
What's mean 'use looking at'?

**Comment by MichaelHillcox** [comment]
In the Gui there is a Button titled 'Add looking at' which will use the exact block you are looking at. Aka, if you're looking at Green wool, it'll add that block instead of that blocks default.
