### ISSUE TITLE
Simple cave-only ores

### ISSUE THREAD

**Issue by Vortecked** [MichaelHillcox/XRay-Mod#154]
So is there a way you can make it so only ores that are touching air blocks show? That would be really helpful. A server my friend owns has an anti X-ray and the only way to bypass is to search for ores that are touching air blocks, since the rest are part of the anti-X-ray. Thanks for reading this if you are, and have a good day I love this mod.

**Comment by MichaelHillcox** [comment]
No, I don’t support using this mod on a public server or on a server where they are trying to stop mods like this being used.
