### ISSUE TITLE
I just have one question

### ISSUE THREAD

**Issue by IHaveOneQuestion** [MichaelHillcox/XRay-Mod#156]
I am trying to install this mod on the 1.7 version, how do I add ores? I am playing on a modded server.

**Comment by MichaelHillcox** [comment]
There is a button in game which you can change in the controls settings of MC. Also, don’t use the mod on a public modded server.

**Comment by IHaveOneQuestion** [comment]
Sorry, it's a friends server and we are lazy but I cannot find the button you are talking about sorry. Could you give some more direction?

**Comment by IHaveOneQuestion** [comment]
I just tried to add an ore from the ore menu and it said it was not supported, am I screwed?

**Comment by MichaelHillcox** [comment]
Hmm, I’m not sure what you mean by unsupported

**Comment by MichaelHillcox** [comment]
1.7 is extremely old, I recommend you update

**Comment by IHaveOneQuestion** [comment]
I tried updating, but would the newer version still work for 1.7.10 mc. 
Also I go to the ore menu and, for example, I put oreMithril. It pops up saying I cannot add ores or smthn like that.

**Comment by MichaelHillcox** [comment]
Sounds like you're adding it incorrectly

**Comment by MichaelHillcox** [comment]
for example, if you have to type the ore which I think you do in 1.7.10 then you likely have to type the ResourceName so for diamonds, it would be `minecraft:diamond_ore`

**Comment by IHaveOneQuestion** [comment]
I’ll test it out, thank you for helping so much. I’ll let you know how it goes.

**Comment by IHaveOneQuestion** [comment]
No dice, minecraft:diamond_ore contains data other than numbers and underscores and doesn’t work.

**Comment by MichaelHillcox** [comment]
Oh, then it's worse. it wants the ID of the block so for diamond ore it would be 56

**Comment by IHaveOneQuestion** [comment]
So I would just type 56?

**Comment by MichaelHillcox** [comment]
Yes

**Comment by IHaveOneQuestion** [comment]
I tried it, it just keeps crashing The game crashed whilst updating screen events
Error: java.lang.ArrayIndexOutOfBoundsException: 1
Exit Code: -1

**Comment by MichaelHillcox** [comment]
Sorry but I don't have the time to support a 6 year old version of the game and this mod. Please update to a newer version of forge or post a real crash log. If you can't update for what ever reason, delete the xray config and try again. I can't help any more.
