### ISSUE TITLE
1.16.4

### ISSUE THREAD

**Issue by randomairborne** [MichaelHillcox/XRay-Mod#157]
1.16.4 update, not much changed that would affect Xray, so all it should need is a JSON and maybe Gradle patch.

**Comment by randomairborne** [comment]
Give me some time and I will try to do it if this is allowed

**Comment by MichaelHillcox** [comment]
It should just work as not much has changed, I’ll check tomorrow

**Comment by yarhoslavme** [comment]
I created a Pull request with an updated version for 1.16.4.  I tested locally and works fine.

**Comment by randomairborne** [comment]
OK, tested and it works great! Thanks!
