### ISSUE TITLE
XRay 1.16 does not pick up blocks

### ISSUE THREAD

**Issue by projectintel-anon** [MichaelHillcox/XRay-Mod#163]
Minecraft 1.16.4, latest version of Forge with BYG mod and Optifine G5. When enabled, XRay doesn't actually find any blocks at all. Distance is set to 48 and tried to find any ores, and nothing showed up - however FPS did dip as it was scanning, but nothing actually appeared. Doesn't work even if BYG is removed or disabled. 

JDK/JRE 14, Ubuntu 20.10 Groovy Gorilla, 5GB RAM dedicated to Minecraft. Tested on a Lenovo V110-15AST 8GB RAM 2133MHz AMD-A9410 RADEON R5 graphics.

**Comment by MichaelHillcox** [comment]
#132
