### ISSUE TITLE
Minecraft Doesnt Work

### ISSUE THREAD

**Issue by BestMemes** [MichaelHillcox/XRay-Mod#168]
The mod works just as fine, but when im done for the day and leave my game, i cant open it anymore
i press play on my optifine or forge version and its just stuck on the "Mojang Studio" Loading screen,
this doesnt happen to the original version.

I tried to reinstall but it just doesnt work, the same thing happens

I would send a crash report, but it didnt crash. It just doesnt load.

 - Minecraft Version: 1.16.4
 - XRay Mod Version: 2.6.0
 - Not using a modpack, just the Launcher
 - Forge Version: 35.1.4

Someone else had the same "Cant open minecraft" problem and the owner said to
Report it to GitHub, so here i am.
I could not find the other Person's report
their username was:
spookedforever
On the curseforge website
I am on Mac: 10.15.7

Optifine:
![Screen Shot 2020-12-20 at 1 32 43 PM](https://user-images.githubusercontent.com/76307354/102709931-2ebd9180-42c8-11eb-9aab-aea5b6ca6221.png)

Forge:
For the Forge one this is different, the "19.9%" on the top would go up and down
![Screen Shot 2020-12-20 at 1 34 48 PM](https://user-images.githubusercontent.com/76307354/102709939-3846f980-42c8-11eb-88fd-8168947521fb.png)

**Comment by MichaelHillcox** [comment]
I test on a mac and I've never had this issue before, you can try and rename you `config/xray/.json` file and see if that allows it to load but that's a long shot idea. Let me know if it happens without my mod installed

**Comment by BestMemes** [comment]
> I test on a mac and I've never had this issue before, you can try and rename you `config/xray/.json` file and see if that allows it to load but that's a long shot idea. Let me know if it happens without my mod installed

I didnt try the config idea yet but minecraft loads after some time without the mod
Only forge works though. (never tried Optifine, ill update once i do)
I've never tried to open the config and i dont know how.

**Comment by MichaelHillcox** [comment]
Likely isn't my mod, please try an isolate the issue and let me know if you still have issues.
