### ISSUE TITLE
searchList is empty inside initGui call!

### ISSUE THREAD

**Issue by bog500** [MichaelHillcox/XRay-Mod#17]
When I click the button to open the XRay menu, a white empty windows pops in minecraft.

In the console, there are those messages:

20:20:12 | game | [00:20:12] [main/INFO]: [STDOUT]: [XRay] --- Populating the searchList with the ore dictionary ---
-- | -- | --
20:20:12 | game | [00:20:12] [main/INFO]: [STDOUT]: [XRay] --- Done populating searchList! ---
20:20:12 | game | [00:20:12] [main/INFO]: [STDOUT]: [XRay] --- Adding custom blocks ---
20:20:12 | game | [00:20:12] [main/INFO]: [STDOUT]: [XRay] --- Done adding custom blocks ---
20:20:12 | game | [00:20:12] [main/INFO]: [STDOUT]: [XRay] Error: searchList is empty inside initGui call!
20:20:13 | game | [00:20:13] [main/INFO]: [STDOUT]: [XRay] --- Populating the searchList with the ore dictionary ---
20:20:13 | game | [00:20:13] [main/INFO]: [STDOUT]: [XRay] --- Done populating searchList! ---
20:20:13 | game | [00:20:13] [main/INFO]: [STDOUT]: [XRay] --- Adding custom blocks ---
20:20:13 | game | [00:20:13] [main/INFO]: [STDOUT]: [XRay] --- Done adding custom blocks ---

I'm not using any mods that add special blocks or items.

Minecraft 1.12
MCP 9.40
Powered by Forge 14.21.1.2387

**Comment by MichaelHillcox** [comment]
Can you update the mod to it's latest version and make sure you've delete the old xray.cfg file and tell me if the issue continues? thanks :)

**Comment by bog500** [comment]
it works.  I must have been using an old version.  I originaly downloaded it from somewhere else.  The latest version (xray-1.12-1.3.2) works fine.
