### ISSUE TITLE
Using XRay-Mod in dev workspace

### ISSUE THREAD

**Issue by hohserg1** [MichaelHillcox/XRay-Mod#170]
**Describe the bug**
Adding mod to dev workspace perform crash

**To Reproduce**
1. Download xray-1.16.4-2.6.0.jar from curse
2. Move to ./run/mods/ directory
3. Run game with `runClient` idea task
4. Wait for loading

**Expected behavior**
Game must load correctly and mod must work

**Crash-report**
https://gist.github.com/hohserg1/b83bc64567775fc224af1450d84c4c8b

**Minecraft Enviorment**
 - Minecraft Version: 1.16.4
 - XRay Mod Version: 1.16.4-2.6.0
 - Forge Version 1.16.4-35.1.10

**Additional context**
I want to use this mod to test worldgen in my mod

**Comment by MichaelHillcox** [comment]
That's not how you use mods in 1.12+ dev env's you need to use your gradle file to import it as a dependency
