### ISSUE TITLE
readme unclear

### ISSUE THREAD

**Issue by randomairborne** [MichaelHillcox/XRay-Mod#173]
Your wording in readme.md is unclear on your stance on use of the mod on servers

**Describe the solution you'd like**
Clarify!

**Describe alternatives you've considered**
You could also just say "Use of this mod on servers is unsupported"

**Additional context**
note on use of the mod on servers: I want to make this very clear, I DO NOT support using this mod on servers, if you create an issue and I see you've tried to join a server, I will close the issue. This mod is only maintained because I personally use it for myself, on my own worlds. Do not break other servers rules, they are there because the owners want you to play a specific way, respect that or play on a different server.

Are you saying no using this mod on servers, or no using this mod on servers that dont allow it? I personally agree with "no servers" but it is still unclear.
You say both
 I DO NOT support using this mod on servers
and
respect that or play on a different server.

**Comment by MichaelHillcox** [comment]
Although I don't personally agree that the readme was unclear. I have made it more direct and presented it as clear as I possibly can. If you find it hand understanding my stance following this update then I can't help you :P

**Comment by randomairborne** [comment]
Thank you, that is much more clear.
