### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by Amartyya-Das** [MichaelHillcox/XRay-Mod#178]
The problem is that all the ores and lava highlights are white/gray, no matter what color I pick. When I Optifine zoom, the color shows up properly. The Minecraft version is 1.16.4 (Forge) and the mod version is 2.6.0.

![image](https://user-images.githubusercontent.com/79083383/107930336-4ba6d600-6f94-11eb-94c7-617748b0f8e1.png)

**Comment by MichaelHillcox** [comment]
#blame-optifine

**Comment by Wip-Sama** [comment]
I have the same problem But I d'nt have optifine installed
my modlist https://i.imgur.com/npWlfHp.png
