### ISSUE TITLE
Request ability to include specific metadata or ignore metadata

### ISSUE THREAD

**Issue by JillSwift** [MichaelHillcox/XRay-Mod#18]
Especially handy for things that are not ores, like the end portal (metadata for direction of block and whether it has an eye of ender installed), stairs, planks...

**Comment by MichaelHillcox** [comment]
Yeah, I might be able to do that. I was thinking about adding back a way to manual add the blocks if you want to so you can use the simple list or the more complicated way of doing it :)

**Comment by MichaelHillcox** [comment]
@JillSwift My latest version will address this issue but please not you will not be able to add non blocks to the system but if you add something like stairs you'll be able to edit the item and then edit it's meta. It's a little funky at the moment but I hope to give the UI a refresh at some point.
