### ISSUE TITLE
[Suggestion] Visibility options

### ISSUE THREAD

**Issue by H0bbitBaron** [MichaelHillcox/XRay-Mod#180]
Thank you for the mod! It's hard to see some highlighting through blocks. Consider may be adding options to:

- hide all other blocks when enabling x-ray
- highlight not only borders but all sides of blocks

As complete alternative may be leave only target blocks visible with standard textures and maximum light as if you and them are floating is space.

**Comment by randomairborne** [comment]
That's what most xrays seem to do 🤔, the main point of this one is that it's different
