### ISSUE TITLE
Thermal expansion ores are not working correctly

### ISSUE THREAD

**Issue by Nexus24** [MichaelHillcox/XRay-Mod#183]
When I select a TE ore, it always shows every type of ore in the mod. (Tin, copper, etc etc)

This happens in the search bar, in the "select in hand" option, and the select looking at option.

I expected this to select the specific ore (Copper) instead of every TE ore.

 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.5.0
 - Pack name/version: A Bit of Everything 3.9.2b

I suspect this issue stems from the fact that TE ores are the same block with different variants. (Such as wool)

**Comment by MichaelHillcox** [comment]
Use the 'looking at' option
