### ISSUE TITLE
Error when trying to use xray mod

### ISSUE THREAD

**Issue by Rxdeus** [MichaelHillcox/XRay-Mod#193]
**Describe the bug**
When I enter forge minecraft, it would pop up saying there's an error trying to load the mod.

**Expected behavior**
I followed the detailed instructions when downloading and adding the mod onto the folder. Assuming there would be no issues.

**Minecraft Enviorment**
 - XRay Mod Version: [1.16.5-2.7.0]
 
 I'm not sure if I did it wrong or why it's not working.

![Screenshot_1](https://user-images.githubusercontent.com/97922561/149847285-169411ca-55a5-468a-b23b-da80979e49bf.png)
![Screenshot_3](https://user-images.githubusercontent.com/97922561/149847288-67b718b9-1df8-4109-a6da-21e6b45433b4.png)

**Comment by MichaelHillcox** [comment]
Crash log please

**Comment by Rxdeus** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/97922561/150010091-cc02a7a7-63ec-4b04-87c9-b17d6fd1dc76.png)
![Screenshot_3](https://user-images.githubusercontent.com/97922561/150010096-2caf8b2e-6645-464d-8274-be1dae6ca8ba.png)
![Screenshot_4](https://user-images.githubusercontent.com/97922561/150010105-868e2d9c-66ee-4c26-a664-a074c6739c69.png)
![Screenshot_5](https://user-images.githubusercontent.com/97922561/150010113-ce10f755-3155-44ab-ae20-e7929f840bf4.png)
![Screenshot_6](https://user-images.githubusercontent.com/97922561/150010120-68e531b5-1af2-4d56-a7d5-49c277f46853.png)

**Comment by Nividica** [comment]
Appears to be a version mismatch. The mod is targeting Minecraft 1.16.5, but it you are using Minecraft version 1.18.1.
From what I can see on the Curseforge page, there is not yet a 1.18 version of this mod.

**Comment by MichaelHillcox** [comment]
see above
