### ISSUE TITLE
Add stuff to en_US.lang

### ISSUE THREAD

**Issue by NatoBoram** [MichaelHillcox/XRay-Mod#22]
I speak french and I would like to add some french translation, however, the [`en_US.lang`](https://github.com/MichaelHillcox/XRay-Mod/blob/master/src/main/resources/assets/xray/lang/en_US.lang) seems to contain very little information. If there was a more complete translation in this file, I could make a `fr_CA.lang` (and maybe an `en_CA.lang`) for French people.

**Comment by MichaelHillcox** [comment]
Translation are next on the todo list and the file you are seeing so far is a very basic seeing if I can make it work kind of thing. Now I know it works I will be moving on with the next update. I will get the en_US.lang file fully up to date within the next 2 days so I'll notify you once it's done 👍  

Thanks for the offer

**Comment by MichaelHillcox** [comment]
I've fully updated the en_US.lang
Please feel free to make a pull request with any new langs. I'm likely going to release the next version to address a few crashing issues but I'd love to support more languages.

I'm going to close this issue but feel free to continue the conversaion here 👍

**Comment by NatoBoram** [comment]
Done! Check out #24.
