### ISSUE TITLE
Screen Freezes Occasionally (Mini Crashes)

### ISSUE THREAD

**Issue by SpeTheof** [MichaelHillcox/XRay-Mod#27]
Hello, I am not sure if this is a discontinued project, but if anyone can contribute to fix this i would be glad to provide more info about the issue

When i enable the XRay Mod and make the chunks get Xrayed it goes 120fps pretty well but occasionally freezes for 1 second and then everything is fine, until it freezes again, like every time it try's to draw outlines or detect blocks screen freezes/crashes for a moment.

Anyone else had this issue?

I have the last version of forge and MC 1.12.2

*edit*
I had no other mods installed, this happens only with this only mod i guess.

**Comment by MichaelHillcox** [comment]
The project is still active. Hmm, I've personally not found this issue on my pc. What is the distances set to and are you doing anything that would be considered abnormal use of the game. As in running any external apps, mods, client mods, etc.

**Comment by SpeTheof** [comment]
Just 8 chunks the least, no i am not

Στις Παρ, 1 Δεκ 2017, 16:26 ο χρήστης Michael Hillcox <
notifications@github.com> έγραψε:

**Comment by SpeTheof** [comment]
I have found the issue, it's my RAM, Java is always capping at 1GB Ram although I have 6GB on my PC, can I increase the limit of how much ram java uses? I have 64 bit Java installed

**Comment by SpeTheof** [comment]
I increased the limit to the ram allocated, but that was not the problem after all. I tried reinstalling NVidia drivers and reset the Nvidia settings  upon installation, everything seems fine now =)

**Comment by SpeTheof** [comment]
(maybe some settings i made from NVidia Control Panel was affecting minecraft, such as 3D Settings)

**Comment by MichaelHillcox** [comment]
Yeah, It did seems like more or a pc issue. I couldn't think of anything in my code that might be using to much ram
