### ISSUE TITLE
Oak Wood Bug

### ISSUE THREAD

**Issue by SpeTheof** [MichaelHillcox/XRay-Mod#29]
When there is a giant oak tree, it just shows the oak wood logs that are not turned sideways, 
https://i.imgur.com/cHwzcJa.png

Kinda annoying if you ask me because the only reason i added xray for giant trees is to find those sided logs xD

**Comment by MichaelHillcox** [comment]
Lol, It's because they have different meta data. You can add all 4 states of meta data into the xray Gui and it'll show them all. Should be as simple a 0 - 3. I'll take a look at this as see about finding a way to locate blocks that have specific position meta states

**Comment by SpeTheof** [comment]
how?

**Comment by MichaelHillcox** [comment]
Add the type of Wood that you want then edit it and change the meta of the block. You can do this in the latest version of the mod :D or though the config.

**Comment by MichaelHillcox** [comment]
This has been resolved as of #50
