### ISSUE TITLE
cant turn off ore if added twice

### ISSUE THREAD

**Issue by Wardevour** [MichaelHillcox/XRay-Mod#3]
Using version MC1.11.2 - 1.1.0.1, I added diamonds again because I wanted them to look green. Now I can't turn them off.

EDIT: I realize this was unnecessary because some conflicting mod (biomes o plenty) was causing them all to appear gray, but there is some issue and the accidental customOre can't be deleted in-game

**Comment by Wardevour** [comment]
Maybe it was because of a space? I called it "better diamond"

**Comment by MichaelHillcox** [comment]
Yeah, No thats a limitation. I'm still yet to touch the mod again. My plan is to just add a delete button if you do this but I don't think its name related. I'm pretty sure it's mod related... Maybe :P 
You need to make sure you add it as in `MODNAME:BLOCKNAME` so for minecraft it would be `minecraft:grass`
