### ISSUE TITLE
xrays not having colors and only showing gray

### ISSUE THREAD

**Issue by gentlewatcher** [MichaelHillcox/XRay-Mod#32]
This is part of a mod pack but it is random for when it works for having colors for the blocks that are pre-set and custom.

**Comment by MichaelHillcox** [comment]
Which version would this be for?

**Comment by gentlewatcher** [comment]
It is for 1.12.2 but I have found something there is a conflict with https://minecraft.curseforge.com/projects/mapwriter-2 version 2.8.1 got the rgb selection and use when the map writer is putting beacon type lights for waypoints.

**Comment by Pigsquidder** [comment]
I have the same issue... It worked until I died and now all the x-ray is only grey. Am using Minecraft 1.12.2 forge with HWYLA, JEI, Map writer, Vein miner and your XRAY.

**Comment by MichaelHillcox** [comment]
Clearly an issue with map writer or my mod. One of them is messing with something they shouldn't be. I'll have a look into both. Quick question... Why not use journey map?

**Comment by Pigsquidder** [comment]
Idk it was the first one I found :/

Anyway what can I do to fix it, or have you not found anything yet?

**Comment by gentlewatcher** [comment]
For me, the map writer seems to be working well for just a basic of what I needed and it may have just been chance while making my pack for 1.12, but as far as the reason behind it I think it is buried in one of the 2 mods for the rgb generation and with the mapwriter for the waypoints use the same style of rgb it seems. ( and the other mods that I have that Pigsquidder listed too was jei (and nei).).

**Comment by MichaelHillcox** [comment]
I'll look at fixing mine. Could either of show me a screenshot of what map writter renders in game that causes the xray mod to go gray?

**Comment by gentlewatcher** [comment]
![minecraft 1 12 2 12_24_2017 7_24_51 pm](https://user-images.githubusercontent.com/34151191/34331026-6500feb6-e8e0-11e7-96a3-1e674264597f.png)
![minecraft 1 12 2 12_24_2017 7_25_18 pm](https://user-images.githubusercontent.com/34151191/34331027-6512542c-e8e0-11e7-8c24-823d60e50ce5.png)

**Comment by MichaelHillcox** [comment]
This is a pretty simple collision with my mod. I'll look at their source and see if I can get it sorted out in the next release

**Comment by MichaelHillcox** [comment]
Related to #45 I'm going to close this one but keep working on finding a way to sort the issue out

**Comment by Cyarutchiii** [comment]
I know the 1.12.2 version has been discontinued, but has this ever gotten fixed? I don't have any of the mentioned mods except for JourneyMap, but even if I delete and disable all waypoints it still shows grey
