### ISSUE TITLE
[1.7.10] Not working on new forge verison

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/XRay-Mod#34]

**Comment by DoomSquirter** [comment]
did the backport ever happen? this is dated in 2018 but last version on CF is from 2016 (1.0.8)

This version doesn't have any rclick functionality on the buttons and the toggle xray doesn't seem to work at all either.  standing right in front of a chest with chest turned on does nothing.

Using forge 10.13.4.1614
