### ISSUE TITLE
Everything renders in light gray ignoring configured color

### ISSUE THREAD

**Issue by calloatti** [MichaelHillcox/XRay-Mod#45]
xray-1.12.2-1.4.2

Every block wireframe renders in light gray (I guess 128,128,128) ignoring configured color.

**Comment by MichaelHillcox** [comment]
Can you confirm whether or not you’ve got any other mods installed that render wireframe like things in the world and if so what mods are they?

**Comment by calloatti** [comment]
I updated some mods (including x-ray) and this started happening, was working correctly before. Will do some testing to try to find the cause and report back. Luckily I save the old mod versions when I update mods.

**Comment by calloatti** [comment]
I rolled back the 4 mods I last updated and it still renders in light gray, no idea what changed to make it not work after it was working until yesterday.

**Comment by MichaelHillcox** [comment]
Hmm, thats very odd. Could you paste bin your config for me?

**Comment by calloatti** [comment]
I found the problem. It happens when I add this mod: 

https://github.com/dmillerw/Impractical-Storage

https://minecraft.curseforge.com/projects/impractical-storage

Before:

![image](https://user-images.githubusercontent.com/12817862/37952467-32f2d10e-3176-11e8-82b1-31b526dee045.png)

After:

![image](https://user-images.githubusercontent.com/12817862/37952482-3fb80e86-3176-11e8-8281-6499a954ccb6.png)

Removing the mod mentioned solves the problem.

**Comment by MichaelHillcox** [comment]
I'll keep the issue open and see if I can resolve the conflict. Thanks for tracking down the conflicting mod :)

**Comment by MichaelHillcox** [comment]
@calloatti Hi, So I've been working on the mod today and I can't make that mod cause the issue. Is there anything you would do that would cause it to do that?

**Comment by calloatti** [comment]
Maybe there is some interaction with another mod? This is the log where you can see all the mods I am using in that instance:

https://paste.ee/p/vW8eQ

The only thing I did was add/remove the mentioned mod jar from the mods folder to reproduce the bug. I did nothing else.

**Comment by calloatti** [comment]
I can upload the exported MultiMC instance zip if you need it.

**Comment by emperor06** [comment]
That may come from both mods playing around with GL Blend. Concurrent access to the drawing. It may be tricky to solve but let's give it a shot.

**Comment by MichaelHillcox** [comment]
I've had a play and I can't seem to get it to happen but if we find the issue to still be happening after the 1.5.0 update then please let us know and re open this issue
