### ISSUE TITLE
Suggestion: In the block list UI, draw the blocks with the selected color wireframe for that block

### ISSUE THREAD

**Issue by calloatti** [MichaelHillcox/XRay-Mod#49]
That way one can easily see what color represents each block. Or any other way you can come up with to relate the ingame wireframes to the corresponding block when one does not remember.

**Comment by MichaelHillcox** [comment]
Sounds like a great idea, I'll see what I can do

**Comment by MichaelHillcox** [comment]
Reminder to self: I might add a colour circle next to the block instead of a wireframe, which ever is simpler.
