### ISSUE TITLE
Suggestion:Extend range

### ISSUE THREAD

**Issue by ShawnFries** [MichaelHillcox/XRay-Mod#56]
It would be useful to (optionally) be able to use a much longer range than just 256 (at least when using rarer blocks like chests so as not to overload the computer).

**Comment by MichaelHillcox** [comment]
We might be able to add a larger radius when our prefermance update comes out but at the moment, something like that regradless of the blocks you want to see would cause a lot of lag. Say you had the range at 512, that would be 512 * 512 * 125 blocks the game would have to scan every tick. ( 32,768,000 )

**Comment by ShawnFries** [comment]
I see, it'd still seem useful for users with powerful computers. Especially if the range could be specified in detail for advanced users, e.g. only looking within 20 blocks vertically to reduce computation costs; or only updating every 30 seconds or something.

I tried to do this myself in a fork, just manually setting the range longer, but couldn't actually manage create a .jar file that I could get to work (I'm not experienced at writing/working with large java projects).

**Comment by MichaelHillcox** [comment]
Hehe, this is a pretty small mod, If you wanna go and scare yourself go and look at AE2 💯 for now, if you wanna fork and create a pull request once you've got a system in place I'd be happy to review it and implement it. 

My thinking is that having an option on the site panel to fine tune the searching that would open a new GUI and show some more specific options would be more than idea. We'd need to expand the settings and adjust the config a little, From what I know we're now using a chunk based system, this would logically mean the adjustments would be possible but might need some intresting thinking :P 

If you want to create a .jar, you'll want to run `gradlew build` and then look in the `build or lib` dir

**Comment by MichaelHillcox** [comment]
Sorry, I have recently been looking at this and our current max is still stressing out most pc's. if we ever find a better way at rendering the ores then we will extend the distance. Currently I feel that 200+ is enough for 99% of the users.

**Comment by MichaelHillcox** [comment]
Unless we find a much better way of finding blocks we'd be looking at a calcuation like this in reference to your own branch:
https://i.imgur.com/h4JdVW9.png
