### ISSUE TITLE
Blocks only added on restart with FTB Revelations 2.0.0

### ISSUE THREAD

**Issue by PloxKevin** [MichaelHillcox/XRay-Mod#58]
xray-1.12.2-1.4.2

New blocks I add are only added when I restart the game. Even a disconnect won't work.

Additionally Cave finder not working

**Comment by MichaelHillcox** [comment]
I think I know about the issue with the blocks not saving and that'll be in the next release.
The cave finder isn't in? have i left it on or something?

**Comment by MichaelHillcox** [comment]
This should be fixed now :D I'm releasing the next version in the next few minutes
