### ISSUE TITLE
Add simpler way to search and add blocks

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/XRay-Mod#6]
I've been getting a lot of feedback about how it's hard to add blocks. I'll improve this in the next version.

Anyone is welcome to do this and submit a pull request. Full credit will be given ❤️

**Comment by Shalar** [comment]
As an idea for this, how about a way to pull the information from the item you are holding. Another thing I think relates to this is allowing the ability to use MOD:BLOCK, or oredict name in the gui.

**Comment by MichaelHillcox** [comment]
My plan was to have a searchable list of blocks like NEI. Although, I know for large mod packs that this could be pretty laggy so I'm trying to work on some code that would allow the list to load with as little lag as possible and search with ease. Although, of course, I'm new to minecraft modding so I'm doing my best. haha. 

The idea of pulling the info from your hand is a great idea, I'll look at adding that. I might also try and make a way to use MOD:BLOCK with some sort of auto complete system. We'll see.

**Comment by MichaelHillcox** [comment]
This has been added as of https://github.com/MichaelHillcox/XRay-Mod/tree/1.12-v1.3.0
