### ISSUE TITLE
Feature Plan for Mobs XRay

### ISSUE THREAD

**Issue by MichaelHillcox** [MichaelHillcox/XRay-Mod#67]
`This is in direct relation to`: #28 

Here is the feature plan for how mobs will work:

- [ ] Live render of mob when hovered on mob name in list
- [ ] A new Gui for adding mobs with a dynamic render of the mob you wish to add
- [ ] Logically a `Outline` of the whole mobs model would be the most logical thing to do to show the mob.
- [ ] Full Mod support
- [ ] A way to select mobs with specific meta
- [ ] Separate Radius to normal Xray
- [ ] Radius menu to display toggle options of [mobs, XRay, Caves]
- [ ] Add Icon for overlay

**Comment by TheDarkLordZ10** [comment]
For the outline, you could "apply"the Glowing effect (similar to spectral arrows). I've seen it in this other mod (Hacker Voice: I'm In)

**Comment by MichaelHillcox** [comment]
Hmm, I think I know what you mean, I don't want to add to much more to the render process but I think its a possibility.
