### ISSUE TITLE
Custom toggle keybind?

### ISSUE THREAD

**Issue by Zafpyr** [MichaelHillcox/XRay-Mod#70]
Because another mod I use, uses the backslash key :(
So the ability to set a custom keybind for toggling XRay would be awesome.

Regards.

**Comment by czp3009** [comment]
change it in game setting(control setting)

**Comment by MichaelHillcox** [comment]
I, thanks for the issue. If you go into your control settings you'll see a section titled Xray, from there you can change the keybinding to what ever you wish

**Comment by Zafpyr** [comment]
Thanks so much, I don't know why I didn't think to check the control settings, naturally I thought if it can be changed the option to do so would be in the ore settings or mod's settings, which this mod has none. 
Well anyway, thank  you!

Regards.
