### ISSUE TITLE
Newly added blocks don't appear until the game is reloaded

### ISSUE THREAD

**Issue by thisischrys** [MichaelHillcox/XRay-Mod#74]
**Describe the bug**
Newly added blocks don't appear until the game is reloaded
**To Reproduce**
1. Add a block
2. Try to find it, fail

**Expected behavior**
Seeing it immediately

**Screenshots**

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.12.2-1.5.0
 - Forge Version: 14.23.4.2732

**Additional context**
Not sure if this is broken in general or a mod conflict, I can post more info if required

**Comment by MichaelHillcox** [comment]
Super weird, You using a mod pack?

**Comment by thisischrys** [comment]
Dw20's 1.12 pack.

**Comment by MichaelHillcox** [comment]
Thanks, I'll fire up an instance and see why it's not working, You added, removed, changed anything in the pack? and did you have an existing config before updating to 1.5.0?

**Comment by MichaelHillcox** [comment]
Related to #72

**Comment by thisischrys** [comment]
I added optifine and some other stuff.
I'll try it with an unaltered install first and let you know when I find.

**Comment by MichaelHillcox** [comment]
@thisischrys does it work without optifine?

**Comment by MichaelHillcox** [comment]
Reopening the issue to make sure I remember to fix this
