### ISSUE TITLE
Crashes when adding blocks

### ISSUE THREAD

**Issue by TheDarkLordZ10** [MichaelHillcox/XRay-Mod#77]
**Describe the bug**

**To Reproduce**
1. open xray GUI
2. Click on "add block" (not hand or looking at)
3. scroll or type
4. Game crashes

**Expected behavior**
To be able to add a block to the xray list using the gui

**Screenshots**
N/A

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.12.2-1.5.0
 - Forge Version: 14.23.4.2739

**Additional context**
Tried multiple times and got the same crash.
[Pastebin Crash Report](https://pastebin.com/cSzDkFFs)

**Comment by MichaelHillcox** [comment]
Thanks for the report. I'm looking to fix this. Please download the config from #76 in my first comment back. Could you confirm if this fixes it?

**Comment by MichaelHillcox** [comment]
Sorry, I read the error wrong. Looks like you are using a pack, could you let me know which pack because the error being called is being called because one of the blocks appears to not have a display name which all of them should have! Damn modders :P

**Comment by TheDarkLordZ10** [comment]
Enigmatica 2 Expert

**Comment by TheDarkLordZ10** [comment]
It only happens in Enigmatica 2 Expert, i dont crash with any other pack (as far as i know)

**Comment by TheDarkLordZ10** [comment]
i think i know what mod crashed it, Recurrent complex, when i scroll down it crashed when i got to that mod, but it gave a different crashlog
[2nd Crash Log](https://pastebin.com/TnyzvU2i)

**Comment by MichaelHillcox** [comment]
thanks :)

**Comment by MichaelHillcox** [comment]
Only through added a tighter exception to the list. I'll add a custom logger to allow people to see who hasn't set it.

**Comment by MichaelHillcox** [comment]
Should be fixed now.
