### ISSUE TITLE
Does not work in multiplayer

### ISSUE THREAD

**Issue by awdwad45456** [MichaelHillcox/XRay-Mod#80]
**Describe the bug**
Everything works perfectly but in multiplayer.

**To Reproduce**
1. Go to 'Muktiplayer'
2. Click on 'Any server'
3. Press X-Ray key, does not work

**Expected behavior**
Pressing X-Ray key and see ores in multiplayer

**Screenshots**

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2] 1.12.2
 - XRay Mod Version: [eg: 1.12.2-1.5.0] latest as of now
 - Forge Version if applicable 1.12.2-forge1.12.2-14.23.4.2756

**Additional context**

**Comment by MichaelHillcox** [comment]
You made be on a sever with a pretty good anti xray?
