### ISSUE TITLE
Xray not showing oak chests.

### ISSUE THREAD

**Issue by TheDreamweaver** [MichaelHillcox/XRay-Mod#81]
**Describe the bug**
Xray does not show oak chest even when added to the list and selected on.

**To Reproduce**
1. Add Oak Chests to xray list.
2. Make sure it's toggled on.
3. Notice how the xray inst highlighting it.

**Expected behavior**
The xray should highlight the chest.

**Minecraft Enviorment**
 - Minecraft Version: 1.12.2
 - XRay Mod Version: 1.12.2-1.5.0
 - Forge Version if applicable: 14.23.4.2715

**Comment by TheDreamweaver** [comment]
The other blocks I have selected (all of which are ore) show up fine.

**Comment by MichaelHillcox** [comment]
Thanks for letting me know, I am currently aware that the is an issue with blocks with specific data states. I'm in the processof sorting this issue out :D

**Comment by MichaelHillcox** [comment]
Relates to #59
