### ISSUE TITLE
Game crash bug detected plz squeeze it.

### ISSUE THREAD

**Issue by bdspark** [MichaelHillcox/XRay-Mod#82]
Describe the bug
While open Xray Gui game crash
Modpack: Sevtech- Ages

To Reproduce
Just open the GUI

Screenshots
N/A

Minecraft Enviorment

Minecraft Version: 1.12.2
XRay Mod Version: 1.12.2-1.5.0 latest as of now
Modpack: Sevtech-Ages
Modpack Ver.- 3.0.8
Forge Version if applicable: No idea

Additional context
I have tested the Xray v.1.5.0 with FTB revelation works fine. But with sevtech- ages pack does not work.

**Comment by MichaelHillcox** [comment]
A crash report would be super helpful,
From what I know it's because one of the mods breaks the gui because it throws an issue up because the mod author of one of the mods hasn't defined one of the item names correctly.

**Comment by MichaelHillcox** [comment]
Thanks for confirming, the error is what I thought it would have been, this has been fixed but has yet to have a new release due to more important underlying issues with the codebase that I'm currently in the process of fixing.

**Comment by bdspark** [comment]
Great work man. your mod is so much fun to use. Hope you release the fix version soon.
keep up the good work and thank you.
