### ISSUE TITLE
A "delete ore" option and bug

### ISSUE THREAD

**Issue by Lexais** [MichaelHillcox/XRay-Mod#83]
**Describe the bug**
I cant turn off some of the ores i added to the menu.

**To Reproduce**
1. Go to the xray menu
2. Create a new ore to find
3. Enter a name but no ID OR Enter an ID with the default name.

**Expected behavior**

**Screenshots**
None

**Minecraft Enviorment**
 - XRay Mod Version: 1.7.10

**Comment by MichaelHillcox** [comment]
It happens when the same block has been added twice due to a bug in the mod. If you right click on the ore you should see a menu to delete the item from the list. 

1.7.10 is no longer supported but I may take a look into fixing it

**Comment by Lexais** [comment]
It's not working, there isnt a menu that comes up

**Comment by MichaelHillcox** [comment]
Hmm, thats odd, make sure you're using the newest version. If all else fails, simply open the config and remove the section for that block and reload the game.
