### ISSUE TITLE
Select multiple entries

### ISSUE THREAD

**Issue by Jajababa** [MichaelHillcox/XRay-Mod#84]
Playing on a Biomes'o'Plenty Server, so there are multiple types of Blocks for the same ore.
Diamond for example got 16 different types of blocks, copper about 50.
It would be nice to be able to select multiple entries at once and give them all the same name/color or some kind of group them.
At the moment i got an extra config for every material, since its getting hell of confusing if you have 50 entrys for every material.

**Comment by MichaelHillcox** [comment]
If I can make it work correctly then this will get done because this would be pretty good to have implemented :)

**Comment by MichaelHillcox** [comment]
Closing for now as with the current implementation of blocks we've got much bigger issues which directly related to modded items doing what you've described. Although I may still add a grouping system to enable and disable a large group of blocks at once.
