### ISSUE TITLE
Conflict with shaders

### ISSUE THREAD

**Issue by LordGeo** [MichaelHillcox/XRay-Mod#86]
![2018-10-30_01 27 10](https://user-images.githubusercontent.com/31355957/47687936-1b7c7300-dbe3-11e8-886c-cb98daad2185.png)
when ever i use any kind of shaders i have the problem of the colors not being shown correctly they either get dulled somewhat or are displayed as black as seen in the screenshot.
furthermore when looking at around sometimes  it just disappears completly or shows the colors correctly for a brief time
any ideas on how to fix it?

**Comment by MichaelHillcox** [comment]
It's likely the mods conflicting on the render tick. I can look into it and see if there is a fairley simple way to fix it. I'll do some testing but I can't promise anything...
