### ISSUE TITLE
Xray doesnt show chest's

### ISSUE THREAD

**Issue by xAtlasx** [MichaelHillcox/XRay-Mod#88]
**Describe the bug**
After adding chest to the list, and enabled it, doesn't show chests

**To Reproduce**
1.Add Chest/oak chest
2. Enable it
3. Doesn't highlight chests

**Expected behavior**
To show chest's

**Screenshots**
Not needed i guess

**Minecraft Enviorment**
MC 1.12.2
Enigmatica 2 Modpack and other modpacks on 1.12.2

**Additional context**
Xray Version 1.50

**Comment by MichaelHillcox** [comment]
Related to #87 #81, will be fixed within the coming weeks.
