### ISSUE TITLE
xray does not show anymore ores after about 4 hours

### ISSUE THREAD

**Issue by xdTRixon** [MichaelHillcox/XRay-Mod#89]
**Describe the bug**

**To Reproduce**
3. ...

**Expected behavior**

**Screenshots**

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.12.2]
 - XRay Mod Version: [eg: 1.12.2-1.5.0]
 - Mod Pack & Version if applicable
 - Forge Version if applicable

**Additional context**

**Comment by xdTRixon** [comment]
When i was using xray about after 4 hours none of the ores where showing

**Comment by MichaelHillcox** [comment]
Could you edit your first post and actually include the information that has been requested? it helps out greatly to figure out what's going on.

**Comment by xdTRixon** [comment]
i have fixed the problem

2018-12-09, sk, 00:48 Michael Hillcox <notifications@github.com> rašė:
