### ISSUE TITLE
Game crashing when i try to add a new ore

### ISSUE THREAD

**Issue by Vorchese** [MichaelHillcox/XRay-Mod#91]

**Comment by MichaelHillcox** [comment]
And the award for best issue goes to @Vorchese could you either use the format or provide the details requested in the format. I need to know the mod version, game version, mod pack if any, crashlog and anything else that might help

**Comment by Vorchese** [comment]
Mod version 1.5.0
Game version 1.12.2
FTB Stoneblock 2
________________________________

**Comment by MichaelHillcox** [comment]
Thanks, this is much more helpful (sorry for such a late response) would you happen to have a crash log?
