### ISSUE TITLE
Chameleon Storage cannot be XRayed

### ISSUE THREAD

**Issue by Neipr** [MichaelHillcox/XRay-Mod#93]
The Chameleon Storage and Dense Chameleon Storage blocks from MultiStorage mod in 1.12.2 cannot be shown by Advanced XRay mod.

It might be because of the fact that these blocks transform themselves into the block that there are in contact with but is ther anyway I could get over that issue ? Maybe with another XRay mod that doesn't have it ?
This issue may be solved by adding these blocks with their ID. How can I do such a thing ?

Thanks a lot, Neipr

**Comment by MichaelHillcox** [comment]
Likely no longer an issue with 1.14. Try adding one of their blocks by looking at it. Odd issue but hopefully one of the 3 addition methods should help :D
