### ISSUE TITLE
Render Blocks though wall

### ISSUE THREAD

**Issue by leschi** [MichaelHillcox/XRay-Mod#94]
** Is your feature request related to a problem? Please describe. **
Well, I always have trouble remembering what the ore is the color.

** Describe the desired solution. **
It would be great if the ores were rendered through the wall or text or something like that.
A legend would also be very helpful.

** Additional context **
I tried to put this function in the code, but I do not have enough experience for this xD

**Comment by MichaelHillcox** [comment]
At the moment I can't do either of these but I'll definitely come back to it after some code improvements. For now I'll close this issue and come back to it :D
