### ISSUE TITLE
Add a search bar

### ISSUE THREAD

**Issue by niklas2233** [MichaelHillcox/XRay-Mod#95]
**Is your feature request related to a problem? Please describe.**
finding what ore to activate
**Describe the solution you'd like**
A search bar to find what ores you have added

**Additional context**
so not when you add a block but when you are activating what ores to xray cause when you play modded minecraft it can get alot of ores and alot of pages

**Comment by MichaelHillcox** [comment]
So a search bar for the main paged list of blocks you've added?

**Comment by niklas2233** [comment]
yes exactly

**Comment by MichaelHillcox** [comment]
https://www.curseforge.com/minecraft/mc-mods/advanced-xray/files/2792282 Released for 1.14 (was already released for 1.12)
