### ISSUE TITLE
Ore Groups or Veins

### ISSUE THREAD

**Issue by bookerthegeek** [MichaelHillcox/XRay-Mod#97]
## Heyo!
Love the mod. Very useful. Also this is not directly related to an specific problem. More of a usability or QoL change.

### Issue
So when playing any pack with any mod that adds ore variants such as UBC or BoP you get a massive list of ores that need to be toggled. That sucks. The other issue is GregTech which adds veins of ores where you get 2-6 different ores spawning next to each other.

### My solution
What I would love would be an option to have a Group/Vein option. This would allow multiple ores to be toggled with one section. Lets take copper for example:
 - GT:CE adds 14 different Copper Ores
 - BoP adds 16 different types
 - UBC adds 16 also I believe
Now, I know that the OreDict option exists but not all mods correctly add OreDict o their ores. Also some of those variants are Stone based, but some are sand, netherrack or endstone.

GT:CE and Railcraft also add Veins. So multiple ores spawning in a specific area right next to each other. In FTB:Interactions
 - 20 different veins just for the over world
 - Each vein can contain between 1 to 6 ore types

#### Additional context
Love the mod. Might be related to #84

**Comment by MichaelHillcox** [comment]
Closed in preference of #129 but definitely still happening soon
