### ISSUE TITLE
Highlight dont work with my custom log block

### ISSUE THREAD

**Issue by hohserg1** [MichaelHillcox/XRay-Mod#98]
**Describe the bug**
I'm try to use this for testing world gen in my mod and my tree log do not highlight in world

**To Reproduce**
1. Go to https://github.com/EndersMagic/EnderMagic/tree/trees
2. Clone and setup
3. Add Advanced Xray to /run/mods/
4. gradlew runClient
5. Add tile.ender_tree_log.name block to xray list by any way(select from list, add block in hand or add looking at)
6. Place block in world
7. On xray

**Expected behavior**
Block of log will be highlighted

**Screenshots**
![](https://i.imgur.com/KgpMf79.png)
![](https://i.imgur.com/JG3DteC.png)
![](https://i.imgur.com/E2gy2Zp.png)
![](https://i.imgur.com/4uU4B5C.png)

**Minecraft Enviorment**
 - Minecraft Version is 1.12.2
 - XRay Mod Version 1.5.0
 - Forge Version is 1.12.2-14.23.5.2768

**Comment by MichaelHillcox** [comment]
Did you try to use `Add looking at` as I suggested?

**Comment by hohserg1** [comment]
![image](https://user-images.githubusercontent.com/35610168/59638706-aeaded00-9161-11e9-9edd-04f03b47921b.png)

**Comment by MichaelHillcox** [comment]
Hmm, jt should at the best least show that specific block. I'll have a look and see what's causing this.

**Comment by MichaelHillcox** [comment]
Likely fixed in 1.14. Let me know if it's not. 1.12 isn't something I really want to go back to :P

**Comment by hohserg1** [comment]
Oh, Ender'sMagic will not be ported to 1.14 in the near future
